USE MASTER
GO

IF EXISTS (SELECT TOP 1 1 FROM SYS.DATABASES WHERE NAME = 'HSL_TESTE')
BEGIN
	ALTER DATABASE [HSL_TESTE] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

	DROP DATABASE IF EXISTS HSL_TESTE
END

CREATE DATABASE HSL_TESTE
